#!/usr/bin/env python3
"""Validate independently generated UMAP geometry facts for formal delivery."""

from __future__ import annotations

import hashlib
import json
from pathlib import Path


FACTS_SCHEMA_VERSION = "1.0.0"
GENERATOR_ID = "sc-marker-cluster-annotation-auto.umap_image_facts"


def sha256_file(path):
    digest = hashlib.sha256()
    with Path(path).open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def canonical_sha256(value):
    payload = json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return hashlib.sha256(payload.encode("utf-8")).hexdigest()


def load_umap_facts(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def validate_umap_facts(facts, expected_clusters, image_path=None, facts_path=None):
    """Fail closed unless facts are complete, hash-bound, and independently generated."""
    errors = []
    if not isinstance(facts, dict):
        return ["UMAP facts must be a JSON object"]
    if facts.get("schema_version") != FACTS_SCHEMA_VERSION:
        errors.append(f"UMAP facts schema_version must be {FACTS_SCHEMA_VERSION}")
    if facts.get("generated_by") != GENERATOR_ID:
        errors.append("UMAP facts must be generated by the registered image-facts tool")
    image_hash = str(facts.get("source_image_sha256", "")).strip().lower()
    if len(image_hash) != 64:
        errors.append("UMAP facts lack source_image_sha256")
    elif image_path:
        actual_image_hash = sha256_file(image_path)
        if image_hash != actual_image_hash:
            errors.append("UMAP facts source_image_sha256 does not match the supplied UMAP image")
    if facts_path:
        declared_facts_hash = str(facts.get("facts_sha256", "")).strip().lower()
        if len(declared_facts_hash) != 64:
            errors.append("UMAP facts lack facts_sha256")
        else:
            payload = dict(facts)
            payload.pop("facts_sha256", None)
            if declared_facts_hash != canonical_sha256(payload):
                errors.append("UMAP facts facts_sha256 does not match its content")
    clusters = facts.get("clusters")
    if not isinstance(clusters, dict):
        errors.append("UMAP facts clusters must be an object")
        return errors
    expected = {str(item) for item in expected_clusters}
    observed = {str(item) for item in clusters}
    if observed != expected:
        errors.append(f"UMAP facts cluster set mismatch: expected={sorted(expected)}, observed={sorted(observed)}")
    for cluster in sorted(expected):
        item = clusters.get(cluster, {})
        if not isinstance(item, dict):
            errors.append(f"UMAP facts cluster {cluster} must be an object")
            continue
        centroid = item.get("centroid")
        if not isinstance(centroid, list) or len(centroid) != 2:
            errors.append(f"UMAP facts cluster {cluster} lacks a two-dimensional centroid")
        if not isinstance(item.get("nearest_clusters"), list):
            errors.append(f"UMAP facts cluster {cluster} lacks nearest_clusters")
        if not isinstance(item.get("adjacent_clusters"), list):
            errors.append(f"UMAP facts cluster {cluster} lacks adjacent_clusters")
        if not str(item.get("component_id", "")).strip():
            errors.append(f"UMAP facts cluster {cluster} lacks component_id")
    return errors


def facts_payload(facts):
    payload = dict(facts)
    payload.pop("facts_sha256", None)
    return payload
